name: CD Pipeline

on:
  push: { }
  workflow_dispatch: { }

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy prometheus
        run: docker compose -f system_monitoring/docker-compose.yml up prometheus -d
      - name: stop grafana
        run: docker compose -f system_monitoring/docker-compose.yml down grafana
      - name: deploy grafana
        run: docker compose -f system_monitoring/docker-compose.yml up grafana -d
